spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

app:
  jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER:global-booking-auth-service}
      audience: ${JWT_AUDIENCE:global-booking-api}
      access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:900000}
      refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:604800000}