-- =========================================================
-- V1 - Initial Auth Service Schema
-- =========================================================

-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL UNIQUE,

    username      VARCHAR(120) NOT NULL,
    email_address VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL,

    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX idx_users_public_id
    ON users (public_id);

CREATE INDEX idx_users_email_address
    ON users (email_address);

CREATE INDEX idx_users_deleted_at
    ON users (deleted_at);