-- =========================================================
-- V4 - Auth Service Schema
-- Status
-- =========================================================

-- =========================================================
-- USERS
-- =========================================================

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID         NOT NULL UNIQUE,

    username      VARCHAR(120) NOT NULL,
    email_address VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL,
    status        VARCHAR(50)  NOT NULL,

    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP
);

-- =========================================================
-- USERS INDEXES
-- =========================================================

CREATE INDEX idx_users_public_id
    ON users (public_id);

CREATE INDEX idx_users_email_address
    ON users (email_address);

CREATE INDEX idx_users_deleted_at
    ON users (deleted_at);


-- =========================================================
-- REFRESH TOKENS
-- =========================================================

CREATE TABLE refresh_tokens
(
    id          UUID        NOT NULL PRIMARY KEY,
    token_id    UUID        NOT NULL UNIQUE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    user_id     BIGINT      NOT NULL,

    expires_at  TIMESTAMP   NOT NULL,
    revoked_at  TIMESTAMP,
    replaced_by UUID,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE
);

-- =========================================================
-- REFRESH TOKENS INDEXES
-- =========================================================

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE INDEX idx_refresh_tokens_revoked_at
    ON refresh_tokens (revoked_at);

CREATE INDEX idx_refresh_tokens_replaced_by
    ON refresh_tokens (replaced_by);